# Generated by Django 4.1 on 2022-10-01 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                max_length=30, validators=[django.core.validators.MinLengthValidator(3)]
            ),
        ),
    ]
