# Generated by Django 4.1 on 2022-09-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Caneta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=45)),
                ("cor", models.CharField(max_length=45)),
                ("ponta", models.CharField(max_length=45)),
            ],
        ),
    ]
