# Generated by Django 4.1 on 2022-10-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caneta", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caneta",
            name="cor",
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name="caneta",
            name="modelo",
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name="caneta",
            name="ponta",
            field=models.CharField(max_length=45, null=True),
        ),
    ]
