# Generated by Django 4.1 on 2022-10-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caneta", "0002_alter_caneta_cor_alter_caneta_modelo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caneta",
            name="cor",
            field=models.CharField(default=" ", max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="caneta",
            name="modelo",
            field=models.CharField(default=" ", max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="caneta",
            name="ponta",
            field=models.CharField(default="", max_length=45),
            preserve_default=False,
        ),
    ]
