# Generated by Django 4.1 on 2022-10-01 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caneta", "0005_alter_caneta_cor_alter_caneta_ponta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caneta",
            name="cor",
            field=models.CharField(
                max_length=45, validators=[django.core.validators.MinLengthValidator(4)]
            ),
        ),
        migrations.AlterField(
            model_name="caneta",
            name="modelo",
            field=models.CharField(
                max_length=45, validators=[django.core.validators.MinLengthValidator(4)]
            ),
        ),
        migrations.AlterField(
            model_name="caneta",
            name="ponta",
            field=models.CharField(
                max_length=45, validators=[django.core.validators.MinLengthValidator(4)]
            ),
        ),
    ]
